"""SQL guardrail — validates SQL generated by the agent before execution.

Ensures only SELECT statements run, blocks destructive keywords, comment
injection, UNION injection, and enforces table allowlists.

Usage:
    from src.guardrails.sql_guardrail import check_sql

    result = check_sql("SELECT revenue FROM sales", datasource="GenericERP")
    if not result["allowed"]:
        raise ValueError(result["reason"])
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_CONFIG_DIR = Path(__file__).resolve().parent.parent.parent / "config"
_DEFAULT_ALLOWLIST_PATH = str(_CONFIG_DIR / "allowlist_config.json")


# ---------------------------------------------------------------------------
# Compiled patterns
# ---------------------------------------------------------------------------

_DESTRUCTIVE_CLAUSE_RE = re.compile(
    r"\b(DROP|TRUNCATE|DELETE|ALTER|INSERT|UPDATE|EXEC(?:UTE)?|MERGE|CALL)\b",
    re.IGNORECASE,
)

_COMMENT_RE = re.compile(r"(--|/\*|\*/)")

_UNION_RE = re.compile(r"\bUNION\b", re.IGNORECASE)

# Table references after FROM or JOIN — skips subqueries that start with (
_TABLE_REF_RE = re.compile(
    r"\b(?:FROM|JOIN)\s+(?!\()"
    r"([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)",
    re.IGNORECASE,
)

# CTE alias names — handles WITH, WITH RECURSIVE, and comma-separated CTEs
_CTE_NAME_RE = re.compile(
    r"(?:WITH(?:\s+RECURSIVE)?|,)\s+([A-Za-z_]\w*)\s+AS\s*\(",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _first_keyword(sql: str) -> Optional[str]:
    """Return the first SQL keyword token, uppercased, or None if unparseable."""
    m = re.match(r"\s*([A-Za-z_]\w*)", sql)
    return m.group(1).upper() if m else None


def _extract_table_names(sql: str) -> set[str]:
    """Extract every table name referenced in FROM and JOIN clauses.

    Strips schema prefixes so 'dbo.customers' is recorded as 'customers'.
    """
    tables: set[str] = set()
    for m in _TABLE_REF_RE.finditer(sql):
        bare = m.group(1).split(".")[-1].lower()
        tables.add(bare)
    return tables


def _extract_cte_names(sql: str) -> set[str]:
    """Return the set of CTE alias names defined in WITH clauses."""
    return {name.lower() for name in _CTE_NAME_RE.findall(sql)}


def _load_allowed_tables(allowlist_path: str, datasource: str) -> Optional[list[str]]:
    """Load the allowed_tables list for *datasource* from the allowlist config.

    Returns None if the file is missing or the datasource is not registered.
    """
    if not os.path.isfile(allowlist_path):
        return None
    with open(allowlist_path, encoding="utf-8") as fh:
        config = json.load(fh)
    for entry in config.get("datasources", []):
        if entry.get("name", "").lower() == datasource.lower():
            return [t.lower() for t in entry.get("allowed_tables", [])]
    return None


# ---------------------------------------------------------------------------
# Individual checks
# ---------------------------------------------------------------------------

def _check_statement_type(sql: str) -> dict:
    """Enforce read-only: only SELECT and WITH are permitted as leading keyword."""
    keyword = _first_keyword(sql)
    if keyword is None:
        return {"allowed": False, "reason": "Blocked: SQL is empty or could not be parsed."}
    if keyword not in ("SELECT", "WITH"):
        return {
            "allowed": False,
            "reason": (
                f"Blocked: only SELECT statements are permitted; "
                f"statement begins with '{keyword}'."
            ),
        }
    return {"allowed": True}


def _check_destructive_clauses(sql: str) -> dict:
    """Scan for destructive keywords anywhere in the SQL."""
    m = _DESTRUCTIVE_CLAUSE_RE.search(sql)
    if m:
        return {
            "allowed": False,
            "reason": (
                f"Blocked: destructive keyword '{m.group(1).upper()}' "
                f"is not permitted anywhere in the SQL."
            ),
        }
    return {"allowed": True}


def _check_comment_injection(sql: str) -> dict:
    """Reject SQL containing comment syntax (-- or /* */)."""
    m = _COMMENT_RE.search(sql)
    if m:
        token = m.group(1)
        style = "block comment (/* */)" if token in ("/*", "*/") else "line comment (--)"
        return {
            "allowed": False,
            "reason": f"Blocked: SQL comment syntax detected ({style}); comments are not permitted.",
        }
    return {"allowed": True}


def _check_union_injection(sql: str) -> dict:
    """Block UNION-based injection attempts."""
    if _UNION_RE.search(sql):
        return {
            "allowed": False,
            "reason": "Blocked: UNION keyword detected; UNION-based injection is not permitted.",
        }
    return {"allowed": True}


def _check_table_allowlist(sql: str, datasource: str, allowlist_path: str) -> dict:
    """Verify every referenced table is in the allowlist for the datasource.

    Fails closed: if the allowlist file is missing or the datasource is not
    registered, the query is blocked.
    """
    allowed = _load_allowed_tables(allowlist_path, datasource)

    if allowed is None:
        return {
            "allowed": False,
            "reason": (
                f"Blocked: datasource '{datasource}' was not found in the allowlist "
                f"config at '{allowlist_path}'. Register the datasource before querying."
            ),
        }

    referenced = _extract_table_names(sql)
    cte_aliases = _extract_cte_names(sql)
    real_tables = referenced - cte_aliases

    disallowed = sorted(t for t in real_tables if t not in allowed)
    if disallowed:
        return {
            "allowed": False,
            "reason": (
                f"Blocked: SQL references table(s) not in the allowlist for "
                f"datasource '{datasource}': {', '.join(disallowed)}."
            ),
        }

    return {"allowed": True}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_sql(
    sql: str,
    datasource: str,
    allowlist_path: str = _DEFAULT_ALLOWLIST_PATH,
) -> dict:
    """Validate SQL produced by the NLQ agent before execution.

    Runs five checks in order:
      1. Statement type    — only SELECT / WITH allowed
      2. Destructive clauses — DROP, DELETE, TRUNCATE, etc. blocked
      3. Comment injection  — -- and /* */ rejected
      4. UNION injection    — UNION keyword rejected
      5. Table allowlist   — every table must be in the allowlist

    Args:
        sql:            The SQL string to validate.
        datasource:     Name of the datasource (must match an entry in the
                        allowlist config, case-insensitive).
        allowlist_path: Path to allowlist_config.json. Defaults to
                        ``config/allowlist_config.json`` relative to repo root.

    Returns:
        ``{"allowed": True}`` if all checks pass, or
        ``{"allowed": False, "reason": "<explanation>"}`` on the first failure.
    """
    if not isinstance(sql, str) or not sql.strip():
        return {"allowed": False, "reason": "Blocked: SQL must be a non-empty string."}

    for check in (
        _check_statement_type,
        _check_destructive_clauses,
        _check_comment_injection,
        _check_union_injection,
    ):
        result = check(sql)
        if not result["allowed"]:
            return result

    return _check_table_allowlist(sql, datasource, allowlist_path)
